name: LLM Agent Trust Verification            

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # run your Action
      - uses: Ballesty-Liam/llm-security-action@v1
        # if you have a custom config file, add:
        # with:
        #   config: .github/llm-policy.yml
